=== David-bzerr/atividades-pos-2024/xml/definicoes.dtd
<!ELEMENT cardapio (pratos+)>
<!ELEMENT pratos (nome, descricao, ingredientes, preco, calorias, tempo)>
<!ATTLIST pratos id ID #REQUIRED>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT tempo (#PCDATA)>

=== David-bzerr/atividades-pos-2024/xml/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">
<cardapio>
    <pratos id="p1">
        <nome>pizza doce</nome>
        <descricao>E doce</descricao>
        <ingredientes>
            <ingrediente>chocolate</ingrediente>
            <ingrediente>tomate</ingrediente>
        </ingredientes>
        <preco>45</preco>
        <calorias>500</calorias>
        <tempo>10 min</tempo>
    </pratos>
    <pratos id="p2">
        <nome>pizza sertaneja</nome>
        <descricao>Tradicional</descricao>
        <ingredientes>
            <ingrediente>carne</ingrediente>
            <ingrediente>tomate</ingrediente>
        </ingredientes>
        <preco>45</preco>
        <calorias>700</calorias>
        <tempo>15 min</tempo>
    </pratos>
    <pratos id="p3">
        <nome>pizza mu√ßarela</nome>
        <descricao>Feito de queijo</descricao>
        <ingredientes>
            <ingrediente>carne</ingrediente>
            <ingrediente>tomate</ingrediente>
        </ingredientes>
        <preco>50</preco>
        <calorias>600</calorias>
        <tempo>15 min</tempo>
    </pratos>
    <pratos id="p4">
        <nome>pizza carne de sol</nome>
        <descricao>E doce</descricao>
        <ingredientes>
            <ingrediente>carne</ingrediente>
            <ingrediente>tomate</ingrediente>
        </ingredientes>
        <preco>45</preco>
        <calorias>800</calorias>
        <tempo>10 min</tempo>
    </pratos>
    <pratos id="p5">
        <nome>pizza sem recheio</nome>
        <descricao>Apenas a massa</descricao>
        <ingredientes>
            <ingrediente>catupiry</ingrediente>
            <ingrediente>massa</ingrediente>
        </ingredientes>
        <preco>25</preco>
        <calorias>200</calorias>
        <tempo>5 min</tempo>
    </pratos>
</cardapio>
